fix: fix issue with wallpapers

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -18,6 +18,15 @@ cd "$HOME"
 system_type=$(uname -s)
 has_apt=$(command -v apt 2>&1 >/dev/null; [ "$?" = "0" ] && (echo 1) || (echo 0))
 
+check_for_install() {
+    # Make it so you can forcibly fail checks
+    if [ "$BOOTSTRAP_FAIL_CHECKS" = "1" ]; then
+        return 1
+    fi
+
+    return check_for_command $1
+}
+
 check_for_command() {
     if which $1 2>&1 >/dev/null; then
         return 0
@@ -50,6 +59,11 @@ setup_msg() {
     gum style --bold --foreground $color_setup "$*"
 }
 
+fatal() {
+    gum style --bold --foreground "#ff0000" "$*" 1>&2
+    exit 1
+}
+
 # Make sure a source installs directory exists
 mkdir -p "$HOME/source-installs"
 
@@ -57,48 +71,50 @@ mkdir -p "$HOME/source-installs"
 if [ "$system_type" = "Linux" ] && [ "$has_apt" = "1" ]; then
     # Perform generic apt update
     echo "Updating apt..."
-    # sudo apt update -qqq
+    sudo apt update -qqq
 
     # Install the base packages
     echo -n "Installing basic packages needed for rest of install... "
-    # sudo apt install ${apt_pkgs_required_base[*]} -qqq
+    sudo apt install ${apt_pkgs_required_base[*]} -qqq
     echo "Done"
 
     # Install everything else
     echo -e "\x1b[1m----- Install -----\x1b[0m"
 
-    if ! check_for_command gum; then
+    if ! check_for_install gum; then
         echo "Installing gum..."
 
         # Add the repository for gum
         sudo mkdir -p /etc/apt/keyrings
         curl -fsSL https://repo.charm.sh/apt/gpg.key | \
-            sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg --batch --yes
+            sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg --batch --yes >/dev/null 2>&1
         echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | \
             sudo tee /etc/apt/sources.list.d/charm.list >/dev/null
         sudo apt update -qqq && sudo apt install gum -qqq
 
         # Verify install
         if ! check_for_command gum; then
-            echo "Failed to install gum!" 1>&2
-            exit 1
+            fatal "Failed to install gum!"
         fi
     else
         already_installed gum
     fi
 
-    if ! check_for_command zsh; then
+    if ! check_for_install zsh; then
         install_msg "Installing zsh..."
         gum spin --title "Installing..." -- apt install zsh -qqq  # Install it
 
         # Verify install
         if ! check_for_command zsh; then
-            echo "Failed to install zsh!" 1>&2
-            exit 1
+            fatal "Failed to install zsh!"
         fi
 
         # Set zsh to default shell
+        install_step_msg "Setting zsh as default shell (requires authentication)..."
         chsh -s $(command -v zsh)
+        if [ "$?" != "0" ]; then
+            fatal "Failed to set zsh as default shell!"
+        fi
 
         # Install OhMyZsh
         install_msg "Installing OhMyZsh..."
@@ -108,7 +124,7 @@ if [ "$system_type" = "Linux" ] && [ "$has_apt" = "1" ]; then
         already_installed zsh
     fi
 
-    if ! check_for_command nvim; then
+    if ! check_for_install nvim; then
         install_msg "Installing NeoVim..."
         
         # Install from source
@@ -125,7 +141,7 @@ if [ "$system_type" = "Linux" ] && [ "$has_apt" = "1" ]; then
         already_installed NeoVim
     fi
 
-    if ! check_for_command sway; then
+    if ! check_for_install sway; then
         install_msg "Installing sway..."
 
         # Install sway itself
@@ -136,6 +152,7 @@ if [ "$system_type" = "Linux" ] && [ "$has_apt" = "1" ]; then
         install_step_spin "Installing dmenu..." -- sudo apt install suckless-tools -qqq
         install_step_spin "Installing tofi..." -- sudo apt install tofi -qqq
         install_step_spin "Installing i3blocks..." -- sudo apt install i3blocks -qqq
+        install_step_spin "Insallling mako..." -- sudo apt install mako-notifier -qqq
         install_step_msg "Installing swaylock-effects (source install)..."
         install_step_spin "Installing dependencies..." -- sudo apt install \
             meson wayland wayland-protocols libxkbcommon cairo libpam0g-dev -qqq
@@ -152,7 +169,7 @@ if [ "$system_type" = "Linux" ] && [ "$has_apt" = "1" ]; then
 
         # Install wallpapers
         install_step_msg "Installing wallpapers..."
-        sudo ln -sf wallpapers/space.jpg /usr/share/backgrounds/space.jpg
+        sudo ln -sf $HOME/wallpapers/space.jpg /usr/share/backgrounds/space.jpg
 
         # Reset the enviorment
         state_reset
@@ -160,14 +177,14 @@ if [ "$system_type" = "Linux" ] && [ "$has_apt" = "1" ]; then
         already_installed sway
     fi
 
-    if ! check_for_command kitty; then
+    if ! check_for_install kitty; then
         install_msg "Installing Kitty Terminal..."
         install_step_spin "Installing..." -- sudo apt install kitty -qqq
     else
         already_installed Kitty Terminal
     fi
 
-    if ! check_for_command google-chrome-beta; then
+    if ! check_for_install google-chrome-beta; then
         install_msg "Installing Google Chrome (Beta)..."
 
         # Add google's repo to apt's sources
@@ -187,7 +204,7 @@ if [ "$system_type" = "Linux" ] && [ "$has_apt" = "1" ]; then
         already_installed "Google Chrome (Beta)"
     fi
 
-    if ! check_for_command gtk-launch && ! check_for_command gtk4-launch; then
+    if ! check_for_install gtk-launch && ! check_for_install gtk4-launch; then
         install_msg "Installing Gtk[2,3,4]..."
         install_step_spin "Installing packages..." -- sudo apt install \
             gtk2-engines-breeze libgtk-4-common libgtk-3.0-common libgtk-2.0-common
